### ISSUE TITLE
Keycloak integration like other SSO

### ISSUE THREAD

**Issue by Allan-Nava** [heroiclabs/nakama#590] opened 2021-04-15 12:13 UTC
Is interesting to integrate Keycloak https://www.keycloak.org/

**Comment by novabyte** [comment] 2021-04-22 09:25
@Allan-Nava This is a duplicate of https://github.com/heroiclabs/nakama/issues/188 . I think we can continue to track demand for the feature request there.

**Closed by novabyte** 2021-04-22 09:25 UTC

**Comment by Allan-Nava** [comment] 2021-04-22 09:29
> @Allan-Nava This is a duplicate of #188 . I think we can continue to track demand for the feature request there.

Ok sorry!
