### ISSUE TITLE
Message read error in one match closing all server authoritative matches. 

### ISSUE THREAD

**Issue by ragavendranbala** [heroiclabs/nakama#636] opened 2021-07-04 07:17 UTC
I'm facing issues like 

"websocket: close 1006 (abnormal closure): unexpected EOF" 

"read tcp 172.20.0.3:7350->106.206.240.93:44654: i/o timeout" (Attached Log files)
Say there are 5 matches running on my server and if one of the match faced these type of issue. it closing all the matches and which are not affected (other 4 matches).

I have raised the issue in forum and waiting for update for a couple of weeks. 

I have attached Docker compose file and Config file. Kindly check this

[Docker Copmpose and config.zip](https://github.com/heroiclabs/nakama/files/6759517/Docker.Copmpose.and.config.zip)

[logfile.log](https://github.com/heroiclabs/nakama/files/6759501/logfile.log)

**Comment by Ragavendran-DX** [comment] 2021-07-13 17:25
More info : 
Unity : 2020.3.12
Nakama Unity Version : 2.9.5
Server version: 20a55b5f+20a55b5f

And Same issue on [v3.4.0]

**Comment by sesposito** [comment] 2021-08-03 13:51
@ragavendranbala I've taken a look at the provided files and the only thing I can infer is that the client seems to be terminating the connection unexepectedly, this could be just bad logic on the client side.

I don't see how the error you're describing would terminate multiple matches uness there's some issue with your match handler code.

Either way I cannot reproduce, so I'll be closing this issue for the time being.

**Closed by sesposito** 2021-08-03 13:51 UTC
