### ISSUE TITLE
Blocked user allowed to send invites to the blocking user

### ISSUE THREAD

**Issue by jeremygram** [heroiclabs/nakama#264] opened 2018-11-16 18:14 UTC
## Description
Blocked players are allowed to send friend requests to the players that blocked them.

## Steps to Reproduce
1. Player A sends an invite to Player B -- `client.AddFriendsAsync()`
2. Player B responds by blocking Player A -- `client.BlockFriendsAsync()`
3. Player A sends another invite to Player B -- `client.AddFriendsAsync()`
4. The invite is allowed to be sent. Player B can accept it, and now we have the impossible scenario of B is blocking A but A is friends with B.

<img width="964" alt="blocked_friends" src="https://user-images.githubusercontent.com/42829035/48639131-92c74a80-e9ca-11e8-8d1f-da14e261c205.png">

## Expected Result
Blocked users should not be allowed to send invites to the players that blocked them.

## Actual Result
An invite from a blocked player is allowed, which can lead to possibly many strange scenarios.

## Context
In this test, Player A was on Android and Player B was in the Unity 2017.4.11f1 editor. The database was empty at the beginning of the test.

## Your Environment

- Nakama: 2.2.0
- Cockroach: 2.0.6
- Environment name and version: Docker Engine: 18.03.1-ce, Compose: 1.21.1
- Operating System and version: macOS High Sierra 10.13.6 (17G65)

**Comment by novabyte** [comment] 2018-11-18 16:20
I've investigated the issue with the inputs you suggested to reproduce. I've attached the social graph (adjacency list) output in the database and other tables alongside my findings.

```

**Comment by novabyte** [comment] 2018-11-18 16:48
I've investigated the issue with the inputs you suggested to reproduce. I've attached the social graph (adjacency list) output in the database and other tables alongside my findings.

The structure of the user accounts is as follows.

I've used these users in my tests:

* User A is `"3968d429-b8ad-425f-a35c-8cf35b73fb0d"`.
* User B is `"afa5189d-b08c-4229-a71c-8ba9f7692bf2"`.

```
|                  id                  |  username  |
| 3968d429-b8ad-425f-a35c-8cf35b73fb0d | MTyGiRIAtj |
| afa5189d-b08c-4229-a71c-8ba9f7692bf2 | VmvDioJXOh |
```

* User A adds User B as a friend.

```
|              source_id               |            destination_id            | state |
| 3968d429-b8ad-425f-a35c-8cf35b73fb0d | afa5189d-b08c-4229-a71c-8ba9f7692bf2 |     1 |
| afa5189d-b08c-4229-a71c-8ba9f7692bf2 | 3968d429-b8ad-425f-a35c-8cf35b73fb0d |     2 |
```

```
|                  id                  |                 subject                 |          content           |
| 1c4b606d-ebc0-4689-8795-80ff1bccfb9a | VmvDioJXOh wants to add you as a friend | {"username": "VmvDioJXOh"} |
```

The user A adds user B and generates a notification to user B with the friend invite. The states are invite_sent(1) and invite_received(2) which are correct. 

* User B blocks User A.

```
|              source_id               |            destination_id            | state |
| afa5189d-b08c-4229-a71c-8ba9f7692bf2 | 3968d429-b8ad-425f-a35c-8cf35b73fb0d |     3 |
```

```
|                  id                  |                 subject                 |          content           |
| 1c4b606d-ebc0-4689-8795-80ff1bccfb9a | VmvDioJXOh wants to add you as a friend | {"username": "VmvDioJXOh"} |
```

The user B blocks the user A which removes the initial friend invite state and marks the reverse relationship as blocked(3). No new notifications are generated which is correct.

* User A adds User B as a friend (again).

```
|              source_id               |            destination_id            | state |
| 3968d429-b8ad-425f-a35c-8cf35b73fb0d | afa5189d-b08c-4229-a71c-8ba9f7692bf2 |     1 |
| afa5189d-b08c-4229-a71c-8ba9f7692bf2 | 3968d429-b8ad-425f-a35c-8cf35b73fb0d |     3 |
```

```
|                  id                  |                 subject                 |          content           |
| 1c4b606d-ebc0-4689-8795-80ff1bccfb9a | VmvDioJXOh wants to add you as a friend | {"username": "VmvDioJXOh"} |
| 81487b32-c613-4556-9110-531067670fab | VmvDioJXOh wants to add you as a friend | {"username": "VmvDioJXOh"} |
```

The user A adds user B as a friend again although they've been blocked by user B. This inserts a new invite_sent(1) relation but does not change or break the original blocked(3) status set by user B. A new notification is sent to user B which announces the invite request. Is this the issue you found?

If the user A attempts to add user B as a friend any number of more times no additional notifications are generated.

@jeremygram Please let me know if this matches your findings.

**Comment by novabyte** [comment] 2018-11-19 09:38
@jeremygram After further investigation we’ve identified the changes to AddFriend to resolve the issue. I've understood what was issue report explained.

It will be part of the next server release.

**Comment by mofirouz** [comment] 2018-11-19 10:54
I've added the fix for this issue on PR https://github.com/heroiclabs/nakama/pull/266:

1. Correctly set the state for invite/invitee
2. Correctly check that you cannot add a friend after blocking them. You'll need to delete first, then add.

**Comment by mofirouz** [comment] 2018-11-19 17:06
The issue is fixed in this commit: https://github.com/heroiclabs/nakama/commit/fd2a4e6cc9e51a7f236c98e90d97f166168e64c1

**Closed by mofirouz** 2018-11-19 17:06 UTC
