### ISSUE TITLE
Nakama server 3.2.1 doesn't start

### ISSUE THREAD

**Issue by sadegh-askari** [heroiclabs/nakama#595] opened 2021-04-19 22:03 UTC
Hi
I download last nakama server (3.2.1) for windows
when i try to start server in cmd, i got this error:
{"level":"fatal","ts":"2021-04-20T02:08:49.858+0430","caller":"migrate/migrate.go:91","msg":"Could not find migrations","error":"open sql\\20180103142001_initial_schema.sql: file does not exist"}

**Comment by novabyte** [comment] 2021-04-19 22:05
@sadegh-askari This could be an issue with how the latest release was packaged. Is it possible you could try the 3.1.1 release of the server and report back?

**Comment by sadegh-askari** [comment] 2021-04-19 22:11
Yes
I downloaded version 3.1.1 And it works properly

**Comment by novabyte** [comment] 2021-04-19 22:14
@sadegh-askari Thanks. I suspect the issue is with the new Go 1.16 embed package we switched over to use and how it handles filesystem paths inside the virtual filesystem on Windows. We'll take a look and patch it as part of the next server release.

**Comment by sadegh-askari** [comment] 2021-04-20 00:00
TNX
I forked server and fix this problem for myself.
but same issue exist when i want to open console at localhost:7351
{"level":"error","ts":"2021-04-20T04:25:01.935+0430","caller":"server/console.go:290","msg":"Failed to open index file.","error":"open ui\\dist\\index.html: file does not exist"}

**Comment by michal-harish** [comment] 2021-04-20 14:43
the fix is ready and tested on windows and osx

**Comment by michal-harish** [comment] 2021-04-22 14:55
@sadegh-askari thanks for raising this. The fix is now merged and will be part of the next release.

**Closed by michal-harish** 2021-04-22 14:55 UTC
