### ISSUE TITLE
Server to server functions input is accepted in an unexpected way

### ISSUE THREAD

**Issue by oott123** [heroiclabs/nakama#205] opened 2018-05-15 04:12 UTC
## Description

Server to server functions have some issues while handling the payload body.

## Steps to Reproduce

As your docs describe, I just created something exactly as the example: 

```lua
local nk = require("nakama")

local function http_handler(context, payload)
  local message = nk.json_encode(payload)
  nk.logger_info(("Message: %q"):format(message))
  return {["context"] = context}
end

nk.register_rpc(http_handler, "http_handler_path")
```

And try to call it:

```bash
curl -X POST "http://127.0.0.1:7350/v2/rpc/http_handler_path?http_key=defaultkey" \
     -d '{"some": "data"}' \
     -H 'Content-Type: application/json' \
     -H 'Accept: application/json'
```

## Actual Result

But I got: 

```json
{"error":"json: cannot unmarshal object into Go value of type string","code":3}
```

## Deeper Information

Actually I found that you treat the whole body as payload, and it should be passed as a JSON string, like:

```bash
curl -X POST "http://127.0.0.1:7350/v2/rpc/http_handler_path?http_key=somekey" \
     -d '"{\"some\": \"data\"}"' \
     -H 'Content-Type: application/json' \
     -H 'Accept: application/json'
```

Please look at this line: `-d '"{\\"some\\": \\"data\\"}"'`. It's a JSON string, which contains a JSON Object serialized as string. What the ...

And what i got in the logger in this case: 

```json
{"level":"info","ts":"2018-05-15T10:51:30.868+0800","msg":"Message: \"\\\"{\\\\\\\"some\\\\\\\": \\\\\\\"data\\\\\\\"}\\\"\""}
```

What a mess.

## Expected Result

I hope that the whole body is treat as payload, unserialize it, and pass it as table to the Lua context.

Like this:

```lua
local nk = require('nakama')
nk.register_rpc(function (context, payload)
  nk.logger_info(payload['some']) -- get "data", no json_decode needed
end, 'func_name')
```

## Environment

```bash
$ ./nakama --version
2.0.0+dev
```

This version is built from commit ea2bfb78e4f37659cd7f39fee54624e03c8d52de .

**Comment by oott123** [comment] 2018-05-15 05:33
And this issue is also exists when returning values from lua. It can only return string values, which I think it should have the ability to return any JSON objects ...

**Comment by jompu** [comment] 2018-06-05 10:40
This issue is still on released 2.0.0.

**Comment by mask3000** [comment] 2018-10-16 09:52
+1

**Comment by novabyte** [comment] 2018-10-16 12:28
@mask3000 The real reason for this issue is that Protocol Buffers had no direct concept which maps between a JSON object and a Protobuf type when we designed the API. So what happens is that the input has to be passed in as an escaped JSON string literal so that it can get through the GRPC gateway and be converted into a JSON object by the API server from the Protobuf string type.

It's possible to solve with an update to the way that endpoint works but it's difficult to do now in a way that doesn't break the current API contract. I'll have a look to assess when the change can be made with least impact.

In the meantime you can have a look at this for how to work around it - https://github.com/heroiclabs/nakama/issues/211#issuecomment-428841407

**Comment by cdiaz** [comment] 2019-07-14 11:40
We still have this difficulty in the new version 2.6.0, consider fixing it soon?

**Comment by novabyte** [comment] 2019-07-14 12:45
@cdiaz I think I've covered in an earlier comment but the problem is that the game server is designed with a protocol buffers API (GRPC) and uses a HTTP gateway around that for wider compatibility with languages and game engines.

Protocol buffers does not have a [data type](https://developers.google.com/protocol-buffers/docs/proto3#scalar) which indicates the input is expected to be JSON. As a result we have no choice but to use a string input type and parse it as JSON later.

All of our official client sdks handle this for you but I'm open to ideas on how we could improve it?

**Comment by zyro** [comment] 2019-07-26 16:23
This is resolved for the general case in 20d6ab3cfc2478c39498a4d261d23c9fd1906ef2 and will be part of the next release.

RPC hooks will accept an optional `unwrap` query parameter and receive/return any raw string payload without wrappers. The documentation will be updated to reflect this in time for the next release.

**Closed by zyro** 2019-07-26 16:23 UTC

**Comment by skitsanos** [comment] 2020-08-26 04:31
```
{"error":"json: cannot unmarshal object into Go value of type string","message":"json: cannot unmarshal object into Go value of type string","code":3}
```

So we are still there even on nakama v.2.12.0+650b506a. Documentation is not updated regarding adding &unwrap=true into query parameters

**Comment by novabyte** [comment] 2020-08-26 09:32
@skitsanos This is not a bug but a side-effect of how GRPC services do not allow unstructured data (JSON) to be described as part of a Protobuf definition. We've provided a workaround as you've seen with the use of `unwrap=true` as a parameter to intercept the raw JSON input direct from the HTTP request. We'll update the docs but this issue is resolved.
