### ISSUE TITLE
Nakama-js can be timeout when pipeline.ProcessRequest return false

### ISSUE THREAD

**Issue by nguyentrannhan** [heroiclabs/nakama#1164] opened 2024-02-02 07:08 UTC
## Description
When pipeline.ProcessRequest return false, the nakama-js can be timeout because the IncommingLoop is break. To fix it, we add a flag for safely break the IncommingLoop

## Steps to Reproduce
1. Run nakama-js-webpack-example
2. Run joinChat with wrong input
3. Errors reported to client and in console log

## Expected Result
nakama-js should return with invalid input error not socket timeout

## Actual Result
Error is thrown with  socket timeout

## Context
- [ ] nakama-js

## Your Environment
- Nakama: 2.7.1
- Database: CockroachDB 
- Environment name and version: Development
- Operating System and version: Window 10/Ubuntu 20.04

**Comment by ftkg** [comment] 2024-02-16 15:57
I don't understand what the issue is supposed to be here and its attempted fix. If you are sending a malformed payload that cannot be processed, the socket will be closed as intended. What is the "wrong input" you are sending in `joinChat`?

**Comment by zyro** [comment] 2024-08-11 16:19
Discussed further [on the PR here](https://github.com/heroiclabs/nakama/pull/1165#issuecomment-2282810237).

**Closed by zyro** 2024-08-11 16:19 UTC
