### ISSUE TITLE
UnlinkApple unlinks successfully even though it is the last link.

### ISSUE THREAD

**Issue by sametguzeldev** [heroiclabs/nakama#1198] opened 2024-04-11 15:04 UTC
## Description
UnlinkApple unlinks even though it is the last link. After unlinking and not having any other links, I am losing the account forever.

## Steps to Reproduce
1. Authenticate with Apple
2. Call UnlinkApple

## Expected Result
Cannot unlink last identifier 

## Actual Result
Unlinked successfully

## Context

- [x] Unity

## Your Environment
- Nakama: 3.16.0
- Database: CockroachDB
- Environment name and version: -
- Operating System and version: Windows 11 Running Docker Desktop. We are using Nakama with Docker.

**Comment by sesposito** [comment] 2024-05-22 17:34
Hello @sametguzeldev, are you sure the account did not have any other identifier associated with it? The logic seems to be correct as far as I can tell.

**Comment by sesposito** [comment] 2024-05-29 17:00
We'll close this issue, please re-open it if you can provide a reproducible example.

**Closed by sesposito** 2024-05-29 17:00 UTC
