### ISSUE TITLE
Hook 'RegisterAfterAddGroupUsers' isn't working

### ISSUE THREAD

**Issue by SaudAliMS** [heroiclabs/nakama#758] opened 2022-01-21 15:20 UTC
## Description
 Hook 'RegisterAfterAddGroupUsers' isn't working on server.

## Steps to Reproduce

1. Create a closed group 
2. Another user sends join request
3. On accepting join request user is added to group but hook 'RegisterAfterAddGroupUsers' isnt called on server

## Expected Result
On accepting join request user is added to group and hook 'RegisterAfterAddGroupUsers' is called on server.

## Actual Result
1. On accepting join request user is added to group but hook 'RegisterAfterAddGroupUsers' isnt called on server

## Tested with

-  Unity

## Your Environment
- Nakama:  3.8.0

**Comment by sesposito** [comment] 2022-01-26 13:49
Hello @SaudAliMS, I was unable to reproduce the issue above, what runtime are you using to register the `AfterAddGroupUsers` hook?

**Comment by SaudAliMS** [comment] 2022-02-16 18:00
Hey @sesposito , Server version: 3.8.0+9e8accdc. Im using typescript.

**Comment by sesposito** [comment] 2022-03-14 14:47
I could not reproduce this on the latest Nakama version, I ran the steps listed above and the JS runtime registered `RegisterAfterAddGroupUsers` hook fired as expected, I will close this issue.

**Closed by sesposito** 2022-03-14 14:47 UTC
