### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by CHiiLD** [heroiclabs/nakama#97] opened 2017-07-22 16:13 UTC
os: osx 10.12.5
golang ver: 1.8.3

`$> git clone https://github.com/heroiclabs/nakama`
`$> cd nakama`
`$> make gettools`
`$> glide install`
install finished, then build

```
$ go build main.go
server/dashboard_accepter.go:22:2: cannot find package "nakama/build/generated/dashboard" in any of:
	/Users/Child/go-workspace/src/nakama/vendor/nakama/build/generated/dashboard (vendor tree)
	/usr/local/Cellar/go/1.8.3/libexec/src/nakama/build/generated/dashboard (from $GOROOT)
	/Users/Child/go-workspace/src/nakama/build/generated/dashboard (from $GOPATH)
cmd/migrate.go:26:2: cannot find package "nakama/build/generated/migration" in any of:
	/Users/Child/go-workspace/src/nakama/vendor/nakama/build/generated/migration (vendor tree)
	/usr/local/Cellar/go/1.8.3/libexec/src/nakama/build/generated/migration (from $GOROOT)
	/Users/Child/go-workspace/src/nakama/build/generated/migration (from $GOPATH)
```

I have no 
`nakama/build/generated/dashboard`
`nakama/build/generated/migration`
packages

how get that?

**Comment by novabyte** [comment] 2017-07-22 16:26
I need to make some improvements to our build system. We don't conform to a straightforward `go build` process because of non-Go dependencies. You'll need to install Protobuf and Node.

@CHiiLD These steps should solve what you need to build a copy of the server:

```
$> cd $GOPATH/src
$> git clone https://github.com/heroiclabs/nakama.git
$> cd dashboard
$> npm install
$> npm run build
$> cd ../
$> make gettools
$> glide install
$> make nakama
```

You'll have a server binary in the "build/dev/" folder. Let me know if you have any other issues.

**Comment by CHiiLD** [comment] 2017-07-23 01:30
solved, just copy
`GOPATH/bin/go-bindata`
`GOPATH/bin/go-protoc-gen-gogoslick `
to
`/usr/local/bin`

and 
`make nakama`

**Comment by mofirouz** [comment] 2017-07-23 07:43
@CHiiLD You are right - We probably should not assume that `GOPATH/bin` is on the `PATH`. This would fix the problem for `go-bindata`. However it won't fix the problem for `go-protoc-gen-gogoslick` as the `protoc` compiler is hardcoded to look for plugins on the `PATH` directly.

We probably should advice people to add `GOPATH/bin` to their `PATH` - unless there is another way?

**Comment by lonewolfaka9** [comment] 2017-09-20 17:15
A better guide on how to build source code will be helpful.
Trying to build from source code since last 1 week and everytime end up with similar mistakes

**Comment by zyro** [comment] 2017-09-20 17:17
@lonewolfaka9 Can you be more specific, what error are you getting? Have you followed the [environment setup and build instructions](https://github.com/heroiclabs/nakama#contribute)?

**Comment by novabyte** [comment] 2018-05-06 14:00
@CHiiLD @lonewolfaka9 We now embed all generated source dependencies in the repo so the project can be built with a simple `go build -i`. I still have plans to support full source builds with Bazel but given the sudden new flux around Go dependency management and `"vgo"` we'll likely wait a little longer for the dust to settle.

**Closed by novabyte** 2018-05-06 14:00 UTC

**Comment by gucheng117** [comment] 2019-04-22 09:36
## Description
Error thrown when install using Docker-Compose,
Stoped at bellow logs:
nakama         | {"level":"info","ts":"2019-04-22T09:26:48.933Z","msg":"Found runtime modules","count":0,"modules":[]}
nakama         | {"level":"info","ts":"2019-04-22T09:26:48.933Z","msg":"Starting Console server for gRPC requests","port":7348}
nakama         | {"level":"info","ts":"2019-04-22T09:26:48.933Z","msg":"Starting Console server gateway for HTTP requests","port":7351}
nakama         | {"level":"info","ts":"2019-04-22T09:26:48.933Z","msg":"Starting API server for gRPC requests","port":7349}
nakama         | {"level":"info","ts":"2019-04-22T09:26:48.934Z","msg":"Starting API server gateway for HTTP requests","port":7350}
nakama         | {"level":"info","ts":"2019-04-22T09:26:49.177Z","msg":"Startup done"}
^CGracefully stopping... (press Ctrl+C again to force)


## Steps to Reproduce
install using Docker-Compose


## Your Environment
- Nakama:2.4.0
- Cockroach: v2.1.4
- Operating System and version: CentOS7.6
