### ISSUE TITLE
nakama 2.5.0 migrate up error with cockroach db v19.1.0.windows-6.2-amd64

### ISSUE THREAD

**Issue by yusufisik** [heroiclabs/nakama#343] opened 2019-04-30 23:39 UTC
`PS C:\SERVER\nakama-2.5.0-windows-amd64> .\nakama migrate up

{"level":"info","ts":"2019-05-01T02:31:30.308+0300","msg":"Database connection","dsn":"root@localhost:26257"}
{"level":"info","ts":"2019-05-01T02:31:30.614+0300","msg":"Database information","version":"CockroachDB CCL v19.1.0 (x86_64-w64-mingw32, built 2019/04/29 18:46:21, go1.11.6)"}
{"level":"info","ts":"2019-05-01T02:31:30.622+0300","msg":"Creating new database","name":"nakama"}
{"level":"fatal","ts":"2019-05-01T02:31:31.219+0300","msg":"Failed to apply migrations","count":1,"error":"pq: constraint \"check_category\" in the middle of being added, try again later handling 20180805174141-tournaments.sql","stacktrace":"github.com/heroiclabs/nakama/migrate.(*migrationService).up\n\t/go/src/github.com/heroiclabs/nakama/migrate/migrate.go:187\ngithub.com/heroiclabs/nakama/migrate.Parse\n\t/go/src/github.com/heroiclabs/nakama/migrate/migrate.go:176\nmain.main\n\t/go/src/github.com/heroiclabs/nakama/main.go:77\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}

PS C:\SERVER\nakama-2.5.0-windows-amd64>`

I started first time cockroach db v19. And on another powershell I started nakama 2.5 fisrt time. It gave me this error. 
Then I tried cockroach v2.1.6, Nakama migrate up function worked without error.
Looks like new cockroach db using different SQL functions. I don't know. I'm not a professional programmer. I'm just hobbyist

My environment: 
windows 10 64bit
nakama 2.5.0

**Comment by mofirouz** [comment] 2019-05-01 10:27
Thanks for letting us know. It definitely looks like there has been a breaking change in Cockroach between 2.1.6 and 19.1.

**Comment by novabyte** [comment] 2019-05-24 07:45
@gupta-vaibhav I think you mentioned on the community channel that you'd identified what has changed in crdb to support their latest release. Would you be able to share the details here and maybe consider a pull request? :)

**Comment by gupta-vaibhav** [comment] 2019-05-24 12:07
Hi, surely I could do a pull request as well. Though I'd like to run by my understanding of the error with you. The problem is with this statement:

```
ALTER TABLE leaderboard
  ADD CONSTRAINT check_category CHECK (category >= 0),
  ADD CONSTRAINT check_duration CHECK (duration >= 0),
  ADD CONSTRAINT check_max_size CHECK (max_size > 0),
  ADD CONSTRAINT check_max_num_score CHECK (max_num_score > 0),
  VALIDATE CONSTRAINT check_category,
  VALIDATE CONSTRAINT check_duration,
  VALIDATE CONSTRAINT check_max_size,
  VALIDATE CONSTRAINT check_max_num_score;
```

is it ok to drop the validate part of the query, given the columns are being added in the same migrate, thus the values can't be in conflict of this constraint. I tested on command line as well. The above query gives the same error that is being returned by migrate up. The following query runs fine.

```
ALTER TABLE leaderboard
  ADD CONSTRAINT check_category CHECK (category >= 0),
  ADD CONSTRAINT check_duration CHECK (duration >= 0),
  ADD CONSTRAINT check_max_size CHECK (max_size > 0),
  ADD CONSTRAINT check_max_num_score CHECK (max_num_score > 0);
```

BTW, breaking the query in two parts will also not work. I tried that, I ran the 'add constraint' first and then tried 'validate constraint', got the same error. So it may be the case that v19.1 has added an implicit validate and we don't need it after all.

Lastly, I tried updating the file '20180805174141-tournaments.sql' to remove the validate constraints bit, but that didn't resolve the issue either. So I guess this depends on how you are running the migrate. I understood that transactions.sql file is just being generated for future reference / use, but not being used directly for migrate up command. And thus I wasn't able to fix it.

But this information should help you fix the issue at your end. Or if you could let me know where the sql query is being read from, I'll be more than happy to fix and create a PR - you know that. :)

**Comment by zyro** [comment] 2019-05-27 12:27
Fixed in 7a5bc56d273b589bf3cf35f27130c8b15de3c6f4 and will be part of the next release.

**Closed by zyro** 2019-05-27 12:27 UTC

**Comment by omid3098** [comment] 2019-06-03 07:47
May I ask when do you plan to release a new version? I want to try nakama and migration up fails on linux too.

**Comment by novabyte** [comment] 2019-06-03 07:51
@omid3098 The current sprint we're in will end in two weeks which is our next scheduled release. In the meantime just use cockroachdb 2.1.6 or Postgres to experiment with the game server. We have Docker compose files which make it extremely easy to try either:

https://github.com/heroiclabs/nakama/blob/master/docker-compose-postgres.yml
https://github.com/heroiclabs/nakama/blob/master/docker-compose.yml

**Comment by omid3098** [comment] 2019-06-03 08:04
Thank you for such a fast response, unforsutately I have no experiences with docker and actually pretty new to server stuffs. so it seems I need to  try with an older version of cockroachdb :)
